spring:
  profiles:
    active:
      - dev

--- # 在单一文件中，可用连续三个连字号（---）区分多个文件

config:
  info: cloud-config-client-dev-4

spring:
  profiles: dev
  application: 
    name: cloud-config-client


---

  
config:
  info: cloud-config-client-dev
  
spring:
  profiles: test
  application: 
    name: cloud-config-client

