spring:
  profiles:
    active:
      - dev

--- # 在单一文件中，可用连续三个连字号（---）区分多个文件
server: 
  port: 8001

spring:
  profiles: dev
  application: 
    name: cloud-provider-dept # 命名当前微服务的名称，这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 填写你数据库的url、登录名、密码和数据库名
    url: jdbc:mysql://192.168.21.206:3306/cloud_DB01?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password:
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.jake.springcloud.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/
  # 细节维护，自定义Eureka服务中心status显示的名称 ,也可以使用默认
  instance:
    instance-id: cloud-provider-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址

# Eureka服务注册中心的`info`超链接的`Error Page`改为提供正确的信息
# 根路径开始添加
info:
  app.name: jake-cloud-provider-dept
  company.name: www.jake.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---

server: 
  port: 8002

spring:
  profiles: test
  application: 
    name: cloud-provider-dept # 命名当前微服务的名称，这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
  datasource:
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 填写你数据库的url、登录名、密码和数据库名
    url: jdbc:mysql://192.168.21.206:3306/cloud_DB02?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password:
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.jake.springcloud.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/
  # 细节维护，自定义Eureka服务中心status显示的名称 ,也可以使用默认
  instance:
    instance-id: cloud-provider-dept8001
    prefer-ip-address: true     #访问路径可以显示IP地址

# Eureka服务注册中心的`info`超链接的`Error Page`改为提供正确的信息
# 根路径开始添加
info:
  app.name: jake-cloud-provider-dept
  company.name: www.jake.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
